export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'
export const SET_KEY = 'SET_KEY'
export const REAL_INFO= 'REAL_INFO'
export const SEARCH= 'SEARCH'
export const CONCAT_ROUTERS= 'CONCAT_ROUTERS'
export const ADD_ROUTERS= 'ADD_ROUTERS'
export const BAR_SWITCH = 'BAR_SWITCH'

export const DEL_ARTICLE = 'DEL_ARTICLE'
export const RESTORE_ARTICLE = 'RESTORE_ARTICLE'